name: chronoflow
description: "An event management platform."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.3
  flutter: ^3.38.9

dependencies:
  adaptive_platform_ui: ^0.1.101
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  netglade_analysis: ^21.0.0

flutter:
  uses-material-design: true
